name: ${project.name}
main: ${project.mainclass}
version: ${project.version}
description: ${project.description}
author: Mics
website: https://mics.tw

depend: [Vault, PowerfulPerms]

commands:
  rgwf:
    description: Remove group with refund.
    usage: /rgwf <user> <group> (-s)
    permission: timedgrouprefund.use
    
permissions:
  timedgrouprefund.use:
    description: can use command /rgwf
    default: op